version: '3'

services:
  db:
    image: mysql:8.0
    container_name: o2-fullstack-challange-bd
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
